---
title: "Class 5: Data Visualization with GGPlot"
author: "Garrett Cole"
format: pdf
---

# Our first ggplot

To use the ggplot2 package I first need to have it installed on my computer.

To install any package we use the 'install.packages()' commands.

Now can I use it? NO! first we need to call 'library(ggplot2)'.

```{r}
#install.packages("ggplot2")
library(ggplot2)
ggplot()
```

```{r}
mpg
```

Our first plot of displ vs hwy All ggplot() graphs are made in the same way.

-   data + aes + geoms

```{r}
ggplot(mpg) + 
  aes(x = displ, y = hwy) +
  geom_point()

ggplot(mpg, aes(displ, hwy)) +
  geom_point()
```

```{r}
ggplot(mpg) + 
  aes(x = displ, y = hwy) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE)
```

```{r}
ggplot(mpg) + 
  aes(x = displ, y = hwy) +
  geom_point() +
  labs(title="Displacement and Highway MPG of Cars",
       x="Displacement (L)", 
       y="Highway MPG (MPH)",
       subtitle = "Your informative subtitle text here",
       caption="Dataset: 'mpg'") +
  geom_smooth(method="lm", se=FALSE) +
  theme_bw()


```

```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)

ggplot(genes) + 
  aes(x = Condition1, y = Condition2, col = State) +
  geom_point() +
  scale_colour_manual(values=c("blue","gray","red")) +
  labs(title="Gene Expresion Changes Upon Drug Treatment",
         x="Control (no drug) ",
         y="Drug Treatment")
```

```{r}
url <- "https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv"

gapminder <- read.delim(url)

# install.packages("dplyr")
library(dplyr)
gapminder_2007 <- gapminder %>% filter(year==2007)

ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.5)

ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, color = pop) +
  geom_point(alpha=0.8)
```

```{r}
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop), alpha=0.7) + 
  scale_size_area(max_size = 10) +
  facet_wrap(~year)
```

```{r}
gapminder_top5 <- gapminder %>% 
  filter(year==2007) %>% 
  arrange(desc(pop)) %>% 
  top_n(5, pop)

ggplot(gapminder_top5) +
  aes(x=reorder(country, -pop), y=pop, fill=country) +
  geom_col(col="gray30") +
  guides(fill="none")
```
